"""Pydantic schemas for the RAG-style query endpoint.

A query returns a citation-backed answer assembled from retrieved chunks. The
answer itself is generated by a temporary deterministic generator (see
``app.services.query``) and these schemas are intentionally LLM-agnostic so the
generator can later be swapped for a real model without changing the contract.
"""

from pydantic import BaseModel, Field


class QueryRequest(BaseModel):
    """A natural-language question to answer from indexed context."""

    question: str = Field(..., description="The question to answer.")
    top_k: int = Field(
        5, ge=1, le=50, description="Number of chunks to retrieve as context."
    )


class QueryCitation(BaseModel):
    """A retrieved chunk cited as evidence for the answer.

    ``filename`` is the human-readable source document name for demo-friendly
    citations; it is optional and falls back to ``document_id`` in the UI when
    absent. ``document_id``/``chunk_id`` are retained for internal traceability.
    """

    document_id: str
    chunk_id: str
    chunk_index: int
    score: float
    text_preview: str
    filename: str | None = None


class QueryResponse(BaseModel):
    """A citation-backed answer for a question, plus retrieval metadata."""

    question: str
    answer: str
    confidence: str
    citations: list[QueryCitation]
    retrieved_count: int
