"""Generate the three SYNTHETIC extended-corpus demo documents for AssetMind AI.

These files complete the demo plant corpus so that the compressor (C-220) and
root-cause-analysis benchmark questions have a real source document to retrieve
from. They are **synthetic hackathon demo data** — internally consistent, but
fictional. No proprietary or copyrighted standard text is reproduced; standards
(API 617, ISO 10816-3, OISD-137, Factories Act) are referenced by number only.

Outputs (written to ``data/documents/``):
    - compressor_datasheet.xlsx       Centrifugal Compressor C-220 datasheet
    - rca_findings_2025.csv           Root-cause analysis findings register
    - sop_compressor_operations.pdf   C-220 operating procedure (startup/shutdown)

Regenerate reproducibly with::

    pip install fpdf2 openpyxl        # data-generation only, not runtime deps
    python data/generate_extended_corpus.py

The generated bytes are deterministic apart from PDF/XLSX embedded timestamps;
the textual content — which is all the ingestion pipeline reads — is fixed.
"""

from __future__ import annotations

import csv
import os

OUT = os.path.join(os.path.dirname(__file__), "documents")
os.makedirs(OUT, exist_ok=True)

SYNTHETIC_BANNER = (
    "SYNTHETIC HACKATHON DEMO DATA - AssetMind AI. Fictional plant asset. "
    "Standards referenced by number only; no proprietary text reproduced."
)


# ─────────────────────────────────────────────────────────────────────────────
# 1. Compressor C-220 datasheet  (compressor_datasheet.xlsx)
# ─────────────────────────────────────────────────────────────────────────────
def make_compressor_datasheet() -> None:
    from openpyxl import Workbook

    # (Section, Parameter, Value, Reference) — every row is tagged to C-220 so
    # asset-scoped retrieval and entity extraction resolve the compressor.
    rows: list[tuple[str, str, str, str]] = [
        ("General", "Service", "Process gas booster - Centrifugal Compressor C-220", "Datasheet CMP-C220-DS-001 Rev 2"),
        ("General", "Machine type", "Centrifugal, 3-stage, horizontally split casing", "Section 1.1"),
        ("General", "Driver", "Electric motor, 1200 kW, 2980 RPM", "Section 1.2"),
        ("General", "Design code", "API 617 (referenced by number only)", "Section 1.3"),
        ("Performance", "Suction pressure", "4.5 bar g", "Section 2.1"),
        ("Performance", "Discharge pressure", "18.0 bar g", "Section 2.2"),
        ("Performance", "Rated flow", "3200 Nm3/h", "Section 2.3"),
        ("Lubrication", "Lube oil grade for C-220", "ISO VG 46 Turbine Oil", "OEM specification sheet section 3.4"),
        ("Lubrication", "Lube oil system", "Forced circulation with twin duplex filter and oil cooler", "Section 3.5"),
        ("Bearings", "High-pressure rotor bearings (DE and NDE)", "Tilt-pad journal bearings", "Section 4.1"),
        ("Bearings", "Thrust bearing", "Double-acting tilting-pad thrust bearing", "Section 4.2"),
        ("Cooling", "Cooling water flow (interstage)", "45 m3/h for interstage cooling", "Section 5.1"),
        ("Cooling", "Cooling water comparison note", "C-220 interstage cooling requires 45 m3/h; by comparison pump P-101 gland cooling requires 5 m3/h", "Section 5.2"),
        ("Cooling", "Cooling water inlet temperature", "32 deg C maximum", "Section 5.3"),
        ("Vibration", "Bearing vibration alarm", "4.5 mm/s RMS per ISO 10816-3 (referenced by number only)", "Section 6.1"),
        ("Spares", "Critical spare parts for C-220", "Bearing pads, rotor kit assemblies, filter mesh screens, and coupling spacer disks", "Section 7.1"),
        ("Spares", "Recommended commissioning spares", "Casing gaskets, shaft O-rings, and instrument fuses", "Section 7.2"),
        ("Notes", "Data classification", SYNTHETIC_BANNER, "-"),
    ]

    wb = Workbook()
    ws = wb.active
    ws.title = "C-220 Datasheet"
    ws.append(["Asset Tag", "Section", "Parameter", "Value", "Reference"])
    for section, parameter, value, reference in rows:
        ws.append(["C-220", section, parameter, value, reference])

    path = os.path.join(OUT, "compressor_datasheet.xlsx")
    wb.save(path)
    print(f"Created: {path} ({len(rows)} data rows)")


# ─────────────────────────────────────────────────────────────────────────────
# 2. RCA findings register  (rca_findings_2025.csv)
# ─────────────────────────────────────────────────────────────────────────────
def make_rca_findings() -> None:
    header = [
        "RCA_ID", "Asset_Tag", "Asset_Type", "Event_Date", "Failure_Mode",
        "Root_Cause", "Contributing_Factors", "Corrective_Action",
        "Recommendation", "Standard_Reference",
    ]
    rows = [
        [
            "RCA-2025-011", "C-220", "compressor", "2025-05-22",
            "Bearing temperature high trip (NDE)",
            "Lube oil filter fouling causing oil flow starvation, leading to friction elevation at NDE bearings",
            "Duplex lube oil filter differential pressure high alarm not actioned; overdue filter changeout",
            "Replaced lube oil filter elements, flushed oil system, and confirmed NDE bearing temperature returned to normal",
            "Add differential-pressure trip on lube oil filter and shorten filter changeout interval",
            "API 617 lubrication guidance (referenced by number only)",
        ],
        [
            "RCA-2025-014", "P-102", "pump", "2025-05-10",
            "Drive-end bearing failure",
            "Grease contamination causing accelerated bearing wear",
            "Incorrect grease type applied at last service and process dust ingress at bearing housing",
            "Replaced DE bearing 6309-2RS and repacked with approved grease Mobilux EP2",
            "Enforce single approved grease and fit bearing isolator seals",
            "OISD-137 vibration monitoring (referenced by number only)",
        ],
        [
            "RCA-2025-008", "P-101", "pump", "2025-01-12",
            "High vibration alarm",
            "Coupling misalignment beyond 0.05 mm TIR following mechanical seal replacement",
            "Alignment not re-verified after maintenance work order closeout",
            "Realigned coupling to within 0.05 mm TIR and replaced drive-end bearing",
            "Make post-maintenance laser alignment a mandatory closeout check",
            "OISD-137 (referenced by number only)",
        ],
    ]

    path = os.path.join(OUT, "rca_findings_2025.csv")
    with open(path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.writer(fh)
        writer.writerow(header)
        writer.writerows(rows)
        # Trailing provenance row keeps the synthetic marker inside the corpus.
        writer.writerow([
            "RCA-NOTE", "-", "-", "-", "-", SYNTHETIC_BANNER, "-", "-", "-", "-",
        ])
    print(f"Created: {path} ({len(rows)} finding rows)")


# ─────────────────────────────────────────────────────────────────────────────
# 3. Compressor operating procedure  (sop_compressor_operations.pdf)
# ─────────────────────────────────────────────────────────────────────────────
def make_compressor_sop() -> None:
    from fpdf import FPDF

    L_MARGIN = R_MARGIN = T_MARGIN = 15

    pdf = FPDF()
    pdf.set_margins(L_MARGIN, T_MARGIN, R_MARGIN)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    def ew() -> float:
        return pdf.w - pdf.l_margin - pdf.r_margin

    def heading(text: str) -> None:
        pdf.set_font("Helvetica", "B", 15)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(ew(), 9, text)

    def sub(text: str) -> None:
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(ew(), 6, text)
        pdf.ln(2)
        pdf.set_draw_color(180, 180, 180)
        pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
        pdf.ln(4)

    def section(title: str, body: str) -> None:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(ew(), 7, title)
        pdf.set_font("Helvetica", size=10)
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(ew(), 6, body)
        pdf.ln(3)

    heading("Standard Operating Procedure: Compressor C-220 Operations")
    sub(
        "SOP ID: SOP-CMP-12  |  Rev: 1  |  Approved: 2025-02-10  |  Applies to: "
        "Centrifugal Compressor C-220  |  " + SYNTHETIC_BANNER
    )

    section(
        "1. Pre-Startup Alignment Checks",
        "1.1 Confirm the maintenance work order for C-220 is closed and the machine "
        "is released to operations.\n"
        "1.2 Verify face and radial alignment of the C-220 coupling within 0.03 mm "
        "using dial gauges.\n"
        "1.3 Check dial deflection through a full shaft rotation and record the "
        "coupling gap in the alignment log.\n"
        "1.4 Confirm lube oil level and that ISO VG 46 turbine oil is charged to the "
        "reservoir.\n"
        "1.5 Confirm interstage cooling water flow is established before rolling the "
        "machine.",
    )

    section(
        "2. Startup Sequence",
        "2.1 Establish lube oil circulation and confirm bearing oil supply pressure "
        "is within range.\n"
        "2.2 Open the compressor recycle (bypass) valve fully to unload the machine.\n"
        "2.3 Energise the driver and bring C-220 to rated speed on recycle.\n"
        "2.4 Confirm bearing vibration is below 4.5 mm/s RMS and NDE/DE bearing "
        "temperatures are within limits.\n"
        "2.5 Slowly load the machine onto the process by closing the recycle valve.",
    )

    section(
        "3. Normal Shutdown",
        "The standard shut down steps for C-220 are: bypass loading, block isolation, "
        "and blowdown depressurization.\n"
        "3.1 Bypass loading: open the recycle (bypass) valve to unload the compressor "
        "before stopping the driver.\n"
        "3.2 Block isolation: close the suction and discharge block valves to isolate "
        "the machine from the process.\n"
        "3.3 Blowdown depressurization: open the blowdown valve to depressurise the "
        "casing to flare before any mechanical work begins.\n"
        "3.4 Maintain lube oil circulation on the post-lube timer until bearing "
        "temperatures fall.",
    )

    section(
        "4. Emergency Shutdown",
        "4.1 Trip the driver from the nearest emergency stop.\n"
        "4.2 Confirm the recycle valve opens and the machine coasts down safely.\n"
        "4.3 Do not restart C-220 until the root cause is identified and a work order "
        "is raised in the CMMS within 30 minutes.",
    )

    section(
        "5. Safety and Isolation",
        "5.1 Apply LOTO per HSE-LOTO-001 before any mechanical work on C-220.\n"
        "5.2 Verify zero energy: casing depressurised, driver isolated, and lube oil "
        "pumps locked out.\n"
        "5.3 Mandatory PPE: safety glasses, gloves, and hearing protection near the "
        "running machine.",
    )

    path = os.path.join(OUT, "sop_compressor_operations.pdf")
    pdf.output(path)
    print(f"Created: {path}")


if __name__ == "__main__":
    make_compressor_datasheet()
    make_rca_findings()
    make_compressor_sop()
    print("\nAll 3 synthetic extended-corpus documents generated in data/documents/")
