"""Canonical demo seed for AssetMind AI.

Seeds the **official demo plant corpus** through the *same* ingestion pipeline
used by the ``POST /documents`` upload route, so the demo index is byte-for-byte
what a user would get by uploading the files themselves. It is:

* **Idempotent** — re-running never double-ingests a document, never duplicates
  chunks/assets/mentions/edges (files already present by filename are skipped and
  knowledge-edge backfill is insert-only).
* **Demo-scoped reset** — ``--reset`` removes only the known demo documents and
  their derived rows (chunks, entities, mentions, orphaned knowledge edges). It
  never deletes user-uploaded documents that are not part of the demo manifest.
* **Loud on partial ingestion** — any document that fails to ingest, or a missing
  expected demo file, causes a non-zero exit.

Usage
-----
    cd apps/api
    PERSISTENCE_BACKEND=postgres \
    DATABASE_URL=postgresql+psycopg://assetmind:assetmind@127.0.0.1:5432/assetmind \
    python -m scripts.seed_demo            # idempotent seed
    python -m scripts.seed_demo --reset    # demo-only clean, then reseed

The corpus mixes real synthetic industrial documents. The compressor datasheet,
compressor SOP and RCA findings are clearly-labelled *synthetic hackathon demo
data* generated by ``data/generate_extended_corpus.py``.
"""

from __future__ import annotations

import argparse
import asyncio
import io
import sys
from pathlib import Path

from fastapi import UploadFile
from sqlalchemy import and_, delete, func, or_, select, update

from app.core import config

# The demo seed is only meaningful against the persistent Postgres index.
config.settings.persistence_backend = "postgres"

from app.db.session import get_database_url, session_scope  # noqa: E402

# ── Official demo plant manifest ─────────────────────────────────────────────
# Assets seeded with canonical display names/types. Ingestion also auto-discovers
# further tags (P-201, BLR-118, TK-482, HX-305, ...) from the documents.
DEMO_ASSETS: list[dict[str, str]] = [
    {"tag": "P-101", "asset_type": "pump", "display_name": "Centrifugal Pump P-101"},
    {"tag": "P-102", "asset_type": "pump", "display_name": "Centrifugal Pump P-102"},
    {"tag": "P-201", "asset_type": "pump", "display_name": "Condensate Pump P-201"},
    {"tag": "V-101", "asset_type": "vessel", "display_name": "Separation Vessel V-101"},
    {"tag": "HX-302", "asset_type": "heat_exchanger", "display_name": "Shell & Tube Exchanger HX-302"},
    {"tag": "C-220", "asset_type": "compressor", "display_name": "Centrifugal Compressor C-220"},
    {"tag": "TK-482", "asset_type": "vessel", "display_name": "Chemical Storage Tank TK-482"},
    {"tag": "BLR-118", "asset_type": "boiler", "display_name": "Package Steam Boiler BLR-118"},
]

# The canonical demo corpus. These filenames define what ``--reset`` may remove;
# nothing outside this list is ever deleted.
DEMO_FILES: list[str] = [
    "pump_oem_manual.pdf",
    "sop_pump_startup.pdf",
    "inspection_report_q1_2025.pdf",
    "compliance_checklist_2025.pdf",
    "work_orders_clean.csv",
    "compressor_datasheet.xlsx",       # synthetic demo data
    "rca_findings_2025.csv",           # synthetic demo data
    "sop_compressor_operations.pdf",   # synthetic demo data
]

_REPO_ROOT = Path(__file__).resolve().parents[3]
_DOCS_DIR = _REPO_ROOT / "data" / "documents"


# ── counts ────────────────────────────────────────────────────────────────────
def _counts(session) -> dict[str, int]:
    from app.db import models as m

    def _count(model) -> int:
        return int(session.execute(select(func.count()).select_from(model)).scalar_one() or 0)

    return {
        "documents": _count(m.Document),
        "chunks": _count(m.DocumentChunk),
        "assets": _count(m.Asset),
        "entities": _count(m.ExtractedEntity),
        "mentions": _count(m.AssetMention),
        "edges": _count(m.KnowledgeEdge),
    }


# ── demo-scoped reset ───────────────────────────────────────────────────────────
def _reset_demo_documents() -> None:
    """Delete only the demo documents and their derived rows.

    Document deletion cascades to chunks, entities and mentions via ON DELETE
    CASCADE. Knowledge edges carry no document/asset foreign key, so any edge
    left dangling by the deletion is pruned explicitly. User-uploaded documents
    outside :data:`DEMO_FILES` are untouched.
    """
    from app.db import models as m

    with session_scope() as session:
        demo_ids = list(
            session.execute(
                select(m.Document.id).where(m.Document.original_filename.in_(DEMO_FILES))
            ).scalars()
        )
        if demo_ids:
            session.execute(delete(m.Document).where(m.Document.id.in_(demo_ids)))
            session.flush()

        # Prune knowledge edges orphaned by the deletion (no FK to cascade them).
        session.execute(
            delete(m.KnowledgeEdge).where(
                or_(
                    and_(
                        m.KnowledgeEdge.target_type == "document",
                        m.KnowledgeEdge.target_id.notin_(select(m.Document.id)),
                    ),
                    and_(
                        m.KnowledgeEdge.target_type == "chunk",
                        m.KnowledgeEdge.target_id.notin_(select(m.DocumentChunk.id)),
                    ),
                    and_(
                        m.KnowledgeEdge.target_type == "entity",
                        m.KnowledgeEdge.target_id.notin_(select(m.ExtractedEntity.id)),
                    ),
                    and_(
                        m.KnowledgeEdge.source_type == "asset",
                        m.KnowledgeEdge.source_id.notin_(select(m.Asset.id)),
                    ),
                )
            )
        )
        print(f"Reset: removed {len(demo_ids)} demo document(s) and pruned orphaned edges.")


# ── asset seeding ───────────────────────────────────────────────────────────────
def _seed_assets() -> None:
    from app.db import models as m
    from app.db import repository as repo

    print("Seeding demo assets...")
    with session_scope() as session:
        for a in DEMO_ASSETS:
            repo.upsert_asset_from_tag(
                tag=a["tag"],
                asset_type=a["asset_type"],
                display_name=a["display_name"],
                session=session,
            )
            # Keep canonical display name/type for known demo tags even if the
            # asset already existed (e.g. auto-created by a prior ingest).
            session.execute(
                update(m.Asset)
                .where(m.Asset.tag == a["tag"])
                .values(asset_type=a["asset_type"], display_name=a["display_name"])
            )
        print(f"  Upserted {len(DEMO_ASSETS)} canonical demo asset(s).")


# ── document ingestion ──────────────────────────────────────────────────────────
async def _ingest_documents() -> list[str]:
    """Ingest any demo file not already present. Returns list of failed filenames."""
    from app.db import repository as repo
    from app.services.ingestion import ingest_upload

    if not _DOCS_DIR.exists():
        raise SystemExit(f"ERROR: documents directory not found at {_DOCS_DIR}")

    with session_scope() as session:
        existing = {doc["original_filename"] for doc in repo.list_documents(session=session)}

    failures: list[str] = []
    for filename in DEMO_FILES:
        path = _DOCS_DIR / filename
        if not path.exists():
            print(f"  MISSING: '{filename}' not found in {_DOCS_DIR}")
            failures.append(filename)
            continue
        if filename in existing:
            print(f"  Skipping: '{filename}' (already ingested)")
            continue
        print(f"  Ingesting: '{filename}'...")
        try:
            upload = UploadFile(filename=filename, file=io.BytesIO(path.read_bytes()), headers=None)
            document = await ingest_upload(upload)
            print(f"    OK: document {document.id} ({document.chunk_count} chunk(s)).")
        except Exception as err:  # noqa: BLE001 - report and fail loudly later
            print(f"    FAILED: '{filename}': {err}")
            failures.append(filename)
    return failures


async def main_async(reset: bool) -> int:
    try:
        get_database_url()
    except Exception as exc:  # pragma: no cover - config guard
        print(f"Database error: {exc}")
        print("Set DATABASE_URL and PERSISTENCE_BACKEND=postgres before running.")
        return 1

    from app.rag import embeddings as rag_embeddings

    if reset:
        _reset_demo_documents()

    _seed_assets()
    failures = await _ingest_documents()

    # Knowledge graph edges (idempotent, insert-only).
    print("\nBackfilling knowledge graph edges...")
    from scripts import backfill_knowledge_edges

    backfill_knowledge_edges.main()

    # ── report ──────────────────────────────────────────────────────────────
    with session_scope() as session:
        counts = _counts(session)
        from app.db import models as m

        present_demo = int(
            session.execute(
                select(func.count()).select_from(m.Document).where(
                    m.Document.original_filename.in_(DEMO_FILES)
                )
            ).scalar_one()
            or 0
        )

    print("\n" + "=" * 48)
    print("Demo seed complete — corpus counts:")
    print(f"  documents          : {counts['documents']}")
    print(f"  chunks             : {counts['chunks']}")
    print(f"  assets             : {counts['assets']}")
    print(f"  facts / entities   : {counts['entities']}")
    print(f"  asset mentions     : {counts['mentions']}")
    print(f"  knowledge edges    : {counts['edges']}")
    print(f"  embedding provider : {rag_embeddings.active_provider()}")
    print(f"  embedding model    : {rag_embeddings.active_model()}")
    print("=" * 48)

    expected_present = sum(1 for f in DEMO_FILES if (_DOCS_DIR / f).exists())
    if failures:
        print(f"\nERROR: {len(failures)} demo document(s) failed to ingest: {failures}")
        return 1
    if present_demo < expected_present:
        print(
            f"\nERROR: partial ingestion — {present_demo}/{expected_present} demo "
            "documents present in the index."
        )
        return 1
    print(f"\nAll {present_demo} demo document(s) present and indexed.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Seed the AssetMind AI demo corpus.")
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Remove only the demo documents (never user uploads) before reseeding.",
    )
    args = parser.parse_args()
    return asyncio.run(main_async(reset=args.reset))


if __name__ == "__main__":
    sys.exit(main())
